apiVersion: v1
kind: Namespace
metadata:
  name: clusternet-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: internal-helm-clusternet-system-clusternet-agent
    meta.helm.sh/release-namespace: clusternet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: clusternet-app-deployer
  namespace: clusternet-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: internal-helm-clusternet-system-clusternet-agent
    meta.helm.sh/release-namespace: clusternet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: clusternet:app:deployer
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: internal-helm-clusternet-system-clusternet-agent
    meta.helm.sh/release-namespace: clusternet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: clusternet:app:deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusternet:app:deployer
subjects:
- kind: ServiceAccount
  name: clusternet-app-deployer
  namespace: clusternet-system

---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-clusternet-agent
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: clusternet-app-deployer
      containers:
      - name: helm
        image: csighub.tencentyun.com/tdcc/helm:3.7.1
        args: ["https://danielxlee.github.io/clusternet-charts"]
      restartPolicy: Never
  backoffLimit: 4


apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm
  namespace: kube-system
  labels:
    app: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
  template:
    metadata:
      labels:
        app: helm
    spec:
      containers:
      - name: helm
        image: ccr.ccs.tencentyun.com/danielxxli/helm:3.7.1
        command: ["/bin/sh", "-c"]
        args: ["sleep 3600"]
