FROM alpine/helm:3.7.1 as builder

FROM bash:5.1.8

COPY --from=builder /usr/bin/helm /usr/local/bin/helm
COPY entrypoint.test /usr/local/bin/entrypoint
COPY clusternet-hub-0.2.0.tgz /
COPY clusternet-agent-0.2.0.tgz /
COPY clusternet-syncer-0.2.0.tgz /

RUN apk add --no-cache git curl && \
    helm plugin install https://github.com/chartmuseum/helm-push.git

WORKDIR /
ENTRYPOINT ["/usr/local/bin/entrypoint"]
